TreatsNSweets/Models/Treat.cs
using System.Collections.Generic;
using System;

namespace TreatsNSweets.Models 
{
  public class Treat 
  {
    public Treat ()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }

    public int TreatId { get; set; }
    public string Name { get; set; }

    public virtual ApplicationUser User { get; set; }

    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }

  }
}

TreatsNSweets/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using TreatsNSweets.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace TreatsNSweets.Controllers
{
  public class TreatsController : Controller
  {
    private readonly TreatsNSweetsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, TreatsNSweetsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [Authorize]
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      _db.Treats.Add(treat);
      _db.SaveChanges();
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }


    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit (Treat treat, int FlavorId)
    {
      if (FlavorId !=0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId});
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if(FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() {FlavorId = FlavorId, TreatId = treat.TreatId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }


    [Authorize]
    public ActionResult Delete (int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    [Authorize]
    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }  

  }
}

TreatsNSweets/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model TreatsNSweets.Models.Treat

<h2>Add a Flavor</h2>

<h4>Add a Flavor to this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  @Html.Label("Select flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

TreatsNSweets/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model TreatsNSweets.Models.Treat

<h4>Add a new treat</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new {required="required"})

  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Add new treat" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all treats", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

TreatsNSweets/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model TreatsNSweets.Models.Treat

<h2>? Are you sure you want to delete this Treat?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("All Treats", "Index")

TreatsNSweets/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model TreatsNSweets.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This treat does not belong to any flavors</p>
}
else
{
  <h4>Flavors this treat belongs to:</h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Flavor.Description</li>
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("All Treats", "Index")</p>
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id=Model.TreatId})</p>

TreatsNSweets/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model TreatsNSweets.Models.Treat

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("All Treats", "Index")</p>

TreatsNSweets/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using TreatsNSweets.Models;
@using System;
@model List<TreatsNSweets.Models.Treat>;

<h1>Treats</h1>

@if (@Model.Count == 0)
{
  <h3>none</h3>
  <h4>@Html.ActionLink("Add Treat", "Create")</h4>
}
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId})</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add Treat", "Create")</p>